app = "ruslan-now"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/ruslandoga/wakatime-2:master"

[env]
  DATABASE_PATH = "/data/w2.db"
  PHX_HOST = "stats.copycat.fun"
  PHX_SERVER = true
  POOL_SIZE = 20

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source = "w2_data_machines"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 2000
    soft_limit = 1500
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
