CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT_DATETIME);
CREATE TABLE IF NOT EXISTS "heartbeats" ("time" REAL NOT NULL, "entity" TEXT NOT NULL, "type" TEXT NOT NULL, "category" TEXT, "project" TEXT, "branch" TEXT, "language" TEXT, "dependencies" TEXT, "lines" INTEGER, "lineno" INTEGER, "cursorpos" INTEGER, "is_write" INTEGER DEFAULT false NOT NULL, "editor" TEXT, "operating_system" TEXT, "machine_name" TEXT) strict;
CREATE INDEX "heartbeats_time_index" ON "heartbeats" ("time");
CREATE TABLE _litestream_seq (id INTEGER PRIMARY KEY, seq INTEGER);
CREATE TABLE _litestream_lock (id INTEGER);
CREATE TABLE IF NOT EXISTS "durations_300" ("id" INTEGER NOT NULL, "start" REAL NOT NULL, "length" REAL NOT NULL, "project" TEXT, "branch" TEXT, "entity" TEXT NOT NULL) STRICT;
CREATE INDEX "durations_300_start_index" ON "durations_300" ("start");
CREATE TABLE IF NOT EXISTS "timers" ("id" INTEGER PRIMARY KEY, "started_at" INTEGER NOT NULL, "finished_at" INTEGER, "task" TEXT NOT NULL);
INSERT INTO schema_migrations VALUES(20220530124959,'2022-05-30T13:52:58');
INSERT INTO schema_migrations VALUES(20220617130706,'2022-06-17T13:20:03');
INSERT INTO schema_migrations VALUES(20220622132459,'2022-06-22T16:35:02');
INSERT INTO schema_migrations VALUES(20220912112929,'2022-09-12T11:30:46');
