name: bench

on:
  pull_request:
  push:
    branches: [master]

jobs:
  elixir:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: bench

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.14.5"
          otp-version: "26"

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-bench-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-bench-

      - run: mix deps.get --only=bench
      - run: mix compile --warnings-as-errors
      - run: make bench
