name: bench

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.13.4"
          otp-version: "25.0.1"

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0-dev.2669+74ed7c1f0

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            sqlite_ext/zig-cache
          key: ${{ runner.os }}-bench-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-bench-

      - name: Install dependencies
        run: mix deps.get --only=bench

      - name: Compile (warnings as errors)
        run: MIX_ENV=bench mix compile --warnings-as-errors

      - name: Compile timeline extension
        run: make timeline

      - name: Bench
        run: make bench
