name: bench

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.14.0"
          otp-version: "25.1"

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-bench-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-bench-

      - name: Install dependencies
        run: mix deps.get --only=bench

      - name: Compile (warnings as errors)
        run: MIX_ENV=bench mix compile --warnings-as-errors

      - name: Bench
        run: make bench
