name: bench

on:
  pull_request:
  push:
    branches: [master]

jobs:
  elixir:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: bench

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: bench-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            bench-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            bench-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-

      - run: mix deps.get --only=$MIX_ENV
      - run: mix compile --warnings-as-errors
      - run: mix do ecto.reset, run bench/heartbeats_insert.exs, run bench/timeline.exs
